name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/checkout@v2
    - name: Use a virtual env
      run: |
        python -m venv .venv
        . .venv/bin/activate
    - name: Install the required packages
      run: |
        pip install tox==4.2.6 poetry==1.2.1
    - name: Lint with black through tox
      run: |
        tox -e black
    - name: Lint with isort through tox
      run: |
        tox -e isort
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/checkout@v2
    - name: Use a virtual env
      run: |
        python -m venv .venv
        . .venv/bin/activate
    - name: Install the required packages
      run: |
        pip install tox==4.2.6 poetry==1.2.1
    - name: Run tests with pytest
      run: |
        tox -e py3
